import { Jost } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import SesstionProvider from "@/context/SessionProvider";
import dynamic from "next/dynamic";

const ToastAlertProvider = dynamic(
  () => import("@/context/ToastAlertProvider"),
  { ssr: false }
);

export const metadata = {
  title: "Doctor Appointment Booking",
  description: "Generated by create next app",
};

const jost = Jost({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased`}>
        <SesstionProvider>
          <ToastAlertProvider />
          <Navbar />
          <main className="min-h-[calc(100vh-72vh)]">{children}</main>
          <Footer />
        </SesstionProvider>
      </body>
    </html>
  );
}
